// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PingAFreelancerInfrastructure.Data;

#nullable disable

namespace PingAFreelancerInfrastructure.Migrations
{
    [DbContext(typeof(PingAFreelancerContext))]
    [Migration("20260811120506_AddGender")]
    partial class AddGender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PingAFreelancerCore.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HoursBilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("InteractionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("LastActive")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("RatingSum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DateContracted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateFulfilled")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateMatched")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DatePinged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HoursContracted")
                        .HasColumnType("int");

                    b.Property<string>("ProposalMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FreelancerId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Labor",
                            PhotoPath = "labor.png"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Domestic",
                            PhotoPath = "domestic.png"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Health",
                            PhotoPath = "health.png"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Lifestyle",
                            PhotoPath = "lifestyle.png"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Tech",
                            PhotoPath = "tech.png"
                        });
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Expertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Expertises");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DomainId = -1,
                            Name = "Carpenter",
                            PhotoPath = "carpenter.png"
                        },
                        new
                        {
                            Id = -2,
                            DomainId = -1,
                            Name = "Chauffeur",
                            PhotoPath = "chauffeur.png"
                        },
                        new
                        {
                            Id = -3,
                            DomainId = -1,
                            Name = "Electrician",
                            PhotoPath = "electrician.png"
                        },
                        new
                        {
                            Id = -4,
                            DomainId = -1,
                            Name = "Furniture Assembler",
                            PhotoPath = "furniture_assembler.png"
                        },
                        new
                        {
                            Id = -5,
                            DomainId = -1,
                            Name = "Packing Service",
                            PhotoPath = "packing_service.png"
                        },
                        new
                        {
                            Id = -6,
                            DomainId = -1,
                            Name = "Painter",
                            PhotoPath = "painter.png"
                        },
                        new
                        {
                            Id = -7,
                            DomainId = -1,
                            Name = "Plumber",
                            PhotoPath = "plumber.png"
                        },
                        new
                        {
                            Id = -8,
                            DomainId = -1,
                            Name = "Roof Repairer",
                            PhotoPath = "roof_repairer.png"
                        },
                        new
                        {
                            Id = -9,
                            DomainId = -1,
                            Name = "Window Cleaner",
                            PhotoPath = "window_cleaner.png"
                        },
                        new
                        {
                            Id = -10,
                            DomainId = -1,
                            Name = "Yard Worker",
                            PhotoPath = "yard_worker.png"
                        },
                        new
                        {
                            Id = -11,
                            DomainId = -2,
                            Name = "Babysitter",
                            PhotoPath = "babysitter.png"
                        },
                        new
                        {
                            Id = -12,
                            DomainId = -2,
                            Name = "Bartender",
                            PhotoPath = "bartender.png"
                        },
                        new
                        {
                            Id = -13,
                            DomainId = -2,
                            Name = "Caregiver",
                            PhotoPath = "caregiver.png"
                        },
                        new
                        {
                            Id = -14,
                            DomainId = -2,
                            Name = "Cook",
                            PhotoPath = "cook.png"
                        },
                        new
                        {
                            Id = -15,
                            DomainId = -2,
                            Name = "Errand Runner",
                            PhotoPath = "errand_runner.png"
                        },
                        new
                        {
                            Id = -16,
                            DomainId = -2,
                            Name = "Gardener",
                            PhotoPath = "gardener.png"
                        },
                        new
                        {
                            Id = -17,
                            DomainId = -2,
                            Name = "Grocery Shopper",
                            PhotoPath = "grocery_shopper.png"
                        },
                        new
                        {
                            Id = -18,
                            DomainId = -2,
                            Name = "Housekeeper",
                            PhotoPath = "housekeeper.png"
                        },
                        new
                        {
                            Id = -19,
                            DomainId = -2,
                            Name = "Housesitter",
                            PhotoPath = "housesitter.png"
                        },
                        new
                        {
                            Id = -20,
                            DomainId = -2,
                            Name = "Kitchen Cleaner",
                            PhotoPath = "kitchen_cleaner.png"
                        },
                        new
                        {
                            Id = -21,
                            DomainId = -2,
                            Name = "Nanny",
                            PhotoPath = "nanny.png"
                        },
                        new
                        {
                            Id = -22,
                            DomainId = -3,
                            Name = "Chiropractor",
                            PhotoPath = "chiropractor.png"
                        },
                        new
                        {
                            Id = -23,
                            DomainId = -3,
                            Name = "Elderly Companion",
                            PhotoPath = "elderly_companion.png"
                        },
                        new
                        {
                            Id = -24,
                            DomainId = -3,
                            Name = "Health Aide",
                            PhotoPath = "health_aide.png"
                        },
                        new
                        {
                            Id = -25,
                            DomainId = -3,
                            Name = "Personal Trainer",
                            PhotoPath = "personal_trainer.png"
                        },
                        new
                        {
                            Id = -26,
                            DomainId = -3,
                            Name = "Physiotherapist",
                            PhotoPath = "physiotherapist.png"
                        },
                        new
                        {
                            Id = -27,
                            DomainId = -3,
                            Name = "Yoga Instructor",
                            PhotoPath = "yoga_instructor.png"
                        },
                        new
                        {
                            Id = -28,
                            DomainId = -4,
                            Name = "Dance Instructor",
                            PhotoPath = "dance_instructor.png"
                        },
                        new
                        {
                            Id = -29,
                            DomainId = -4,
                            Name = "Image Consultant",
                            PhotoPath = "image_consultant.png"
                        },
                        new
                        {
                            Id = -30,
                            DomainId = -4,
                            Name = "Interior Designer",
                            PhotoPath = "interior_designer.png"
                        },
                        new
                        {
                            Id = -31,
                            DomainId = -4,
                            Name = "Music Teacher",
                            PhotoPath = "music_teacher.png"
                        },
                        new
                        {
                            Id = -32,
                            DomainId = -4,
                            Name = "Photographer",
                            PhotoPath = "photographer.png"
                        },
                        new
                        {
                            Id = -33,
                            DomainId = -4,
                            Name = "Stylist",
                            PhotoPath = "stylist.png"
                        },
                        new
                        {
                            Id = -34,
                            DomainId = -4,
                            Name = "Tutor",
                            PhotoPath = "tutor.png"
                        },
                        new
                        {
                            Id = -35,
                            DomainId = -5,
                            Name = "Appliance Guy",
                            PhotoPath = "appliance_guy.png"
                        },
                        new
                        {
                            Id = -36,
                            DomainId = -5,
                            Name = "Security Camera Guy",
                            PhotoPath = "security_camera_guy.png"
                        },
                        new
                        {
                            Id = -37,
                            DomainId = -5,
                            Name = "Smart Home Guy",
                            PhotoPath = "smart_home_guy.png"
                        },
                        new
                        {
                            Id = -38,
                            DomainId = -5,
                            Name = "Wifi Guy",
                            PhotoPath = "wifi_guy.png"
                        });
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Freelancer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ExpertiseId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("HoursBilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("InteractionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("LastActive")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RatingSum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalEarned")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("Email");

                    b.HasIndex("ExpertiseId");

                    b.ToTable("Freelancers");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Contract", b =>
                {
                    b.HasOne("PingAFreelancerCore.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PingAFreelancerCore.Entities.Freelancer", "Freelancer")
                        .WithMany("Contracts")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Expertise", b =>
                {
                    b.HasOne("PingAFreelancerCore.Entities.Domain", "Domain")
                        .WithMany("Expertises")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Freelancer", b =>
                {
                    b.HasOne("PingAFreelancerCore.Entities.Domain", "Domain")
                        .WithMany("Freelancers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PingAFreelancerCore.Entities.Expertise", "Expertise")
                        .WithMany("Freelancers")
                        .HasForeignKey("ExpertiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Expertise");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Domain", b =>
                {
                    b.Navigation("Expertises");

                    b.Navigation("Freelancers");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Expertise", b =>
                {
                    b.Navigation("Freelancers");
                });

            modelBuilder.Entity("PingAFreelancerCore.Entities.Freelancer", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
